"""Initial migration - all models

Revision ID: 78d60fdb7bf4
Revises: 
Create Date: 2025-11-10 17:14:18.849030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d60fdb7bf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_projects_required_skills'), table_name='projects', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_projects_required_skills'), 'projects', ['required_skills'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
